project:
  type: book
  output-dir: docs

book:
  title: "pcibex_tutorial"
  author: "Kirill Chuprinko"
  date: "3/30/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - common_things.qmd
    - sprt.qmd
    - sgj.qmd
    - after_coding.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

